import type { IndicatorCategory, IndicatorConfig } from "@/lib/estat/types";

export const CATEGORY_LABELS: Record<IndicatorCategory, string> = {
  housing: "住宅・建設",
  regional: "地域別",
  macro: "マクロ経済",
  employment: "雇用・所得",
  consumption: "消費・物価",
};

export const SUMMARY_INDICATOR_IDS = [
  "housing-starts-total",
  "construction-orders-private-building",
  "cpi-all-items",
  "unemployment-rate",
  "industrial-production",
  "nominal-wage-index",
] as const;

export const INDICATORS: IndicatorConfig[] = [
  {
    id: "housing-starts-total",
    sourceType: "dashboard",
    category: "housing",
    title: "新設住宅着工戸数",
    sourceName: "建築着工統計調査報告 資料2",
    preferredIndicatorCodes: ["0802010103000010000"],
    dashboard: { cycle: "1", regionalRank: "2", isSeasonalAdjustment: "1" },
    statSearchKeyword: "【住宅】季節調整値 戸数",
    statsCode: "00600120",
    preferredTableIds: ["0003119772"],
    tableTitleIncludes: ["季節調整値", "戸数"],
    unit: "戸",
    calcMode: "yoy",
    changeType: "percent",
    selectors: { tab: "91", cat01: "11" },
    periodStrategy: "timeCode",
    notes: "直近公表の月次原系列を使い、住宅需要の足元を前年同月比で確認します。",
    summary: true,
  },
  {
    id: "housing-starts-owner",
    sourceType: "dashboard",
    category: "housing",
    title: "持家着工戸数",
    sourceName: "建築着工統計調査報告 資料2",
    preferredIndicatorCodes: ["0802010103010010010"],
    dashboard: { cycle: "1", regionalRank: "2", isSeasonalAdjustment: "1" },
    statSearchKeyword: "【住宅】季節調整値 戸数",
    statsCode: "00600120",
    preferredTableIds: ["0003119772"],
    tableTitleIncludes: ["季節調整値", "戸数"],
    unit: "戸",
    calcMode: "yoy",
    changeType: "percent",
    selectors: { tab: "91", cat01: "12" },
    periodStrategy: "timeCode",
    notes: "持家の着工動向を月次原系列で追い、前年同月比で変化を見ます。",
  },
  {
    id: "housing-starts-rental",
    sourceType: "dashboard",
    category: "housing",
    title: "貸家着工戸数",
    sourceName: "建築着工統計調査報告 資料2",
    preferredIndicatorCodes: ["0802010103010010020"],
    dashboard: { cycle: "1", regionalRank: "2", isSeasonalAdjustment: "1" },
    statSearchKeyword: "【住宅】季節調整値 戸数",
    statsCode: "00600120",
    preferredTableIds: ["0003119772"],
    tableTitleIncludes: ["季節調整値", "戸数"],
    unit: "戸",
    calcMode: "yoy",
    changeType: "percent",
    selectors: { tab: "91", cat01: "13" },
    periodStrategy: "timeCode",
    notes: "貸家着工の月次原系列を用い、賃貸・投資需要の変化を前年同月比で見ます。",
  },
  {
    id: "housing-starts-for-sale",
    sourceType: "dashboard",
    category: "housing",
    title: "分譲住宅着工戸数",
    sourceName: "建築着工統計調査報告 資料2",
    preferredIndicatorCodes: ["0802010103010010030"],
    dashboard: { cycle: "1", regionalRank: "2", isSeasonalAdjustment: "1" },
    statSearchKeyword: "【住宅】季節調整値 戸数",
    statsCode: "00600120",
    preferredTableIds: ["0003119772"],
    tableTitleIncludes: ["季節調整値", "戸数"],
    unit: "戸",
    calcMode: "yoy",
    changeType: "percent",
    selectors: { tab: "91", cat01: "15" },
    periodStrategy: "timeCode",
    notes: "分譲住宅の着工を月次原系列で捉え、販売動向の変化を前年同月比で確認します。",
  },
  {
    id: "construction-orders-private-building",
    sourceType: "estat",
    category: "housing",
    title: "建設受注（民間・建築）",
    sourceName: "建設工事受注動態統計調査報告 受注高時系列",
    statSearchKeyword: "受注高 民間 建築 月次",
    statsCode: "00600130",
    preferredTableIds: ["0003458298"],
    tableTitleIncludes: ["工事種類別受注高時系列表"],
    unit: "百万円",
    calcMode: "yoy",
    changeType: "percent",
    selectors: { tab: "300", cat01: "120", cat02: "130" },
    periodStrategy: "timeCode",
    notes: "民間建築受注は非住宅・大型案件を含む先行感の確認に向きます。",
    summary: true,
  },
  {
    id: "public-construction-orders",
    sourceType: "dashboard",
    category: "housing",
    title: "公共工事受注額",
    sourceName: "建設工事受注動態統計調査（建設工事統計調査）",
    searchKeyword: "公共工事受注額",
    preferredIndicatorCodes: ["0802020202000010010"],
    regionSupport: "national",
    unit: "百万円",
    calcMode: "yoy",
    changeType: "percent",
    selectors: { area: "00000" },
    dashboard: { cycle: "1", regionalRank: "2", isSeasonalAdjustment: "1" },
    freshnessPolicy: { allowedCycles: ["month"], maxLagMonths: 4 },
    staleBehavior: "hide",
    notes: "統計ダッシュボード API の月次系列で、公共投資寄りの建設需要を確認します。",
  },
  {
    id: "construction-cost-deflator-housing",
    sourceType: "estat",
    category: "housing",
    title: "建設工事費デフレーター（住宅総合）",
    sourceName: "建設工事費デフレーター 時系列（月別）",
    statSearchKeyword: "工事費デフレーター",
    statsCode: "00600270",
    preferredTableIds: ["0003447801"],
    tableTitleIncludes: ["2015年度基準", "月別"],
    unit: "指数",
    calcMode: "yoy",
    changeType: "percent",
    selectors: { tab: "100", cat01: "120", cat02: "2015" },
    periodStrategy: "timeCode",
    notes: "建設コスト環境の把握に有効で、価格転嫁や採算感の参考になります。",
  },
  {
    id: "renovation-orders-housing",
    sourceType: "estat",
    category: "housing",
    title: "リフォーム受注高（住宅）",
    sourceName: "建築物リフォーム・リニューアル調査 四半期",
    statSearchKeyword: "リニューアル 受注高",
    statsCode: "00600900",
    preferredTableIds: ["0003361019"],
    tableTitleIncludes: ["受注高の推移"],
    unit: "億円",
    calcMode: "yoy",
    changeType: "percent",
    selectors: { tab: "150", cat01: "110" },
    periodStrategy: "timeCode",
    notes: "改修需要の足元を見る四半期系列で、住宅ストック市場の把握に使えます。",
  },
  {
    id: "gdp-real",
    sourceType: "dashboard",
    category: "macro",
    title: "実質GDP",
    sourceName: "四半期別GDP速報 実質季節調整系列",
    preferredIndicatorCodes: ["0705020401000010000"],
    dashboard: { cycle: "2", regionalRank: "2", isSeasonalAdjustment: "2" },
    statSearchKeyword: "国内総生産 四半期 実質季節調整系列",
    statsCode: "00100409",
    preferredTableIds: ["0003376031"],
    tableTitleIncludes: ["国内総生産", "実質季節調整系列"],
    unit: "10億円",
    calcMode: "qoq",
    changeType: "percent",
    selectors: { tab: "11", cat01: "11" },
    periodStrategy: "timeCode",
    notes: "景気全体の基調を見る代表的な四半期指標です。",
  },
  {
    id: "cpi-all-items",
    sourceType: "estat",
    category: "macro",
    title: "CPI総合",
    sourceName: "2020年基準消費者物価指数",
    statSearchKeyword: "消費者物価指数 総合 月次",
    statsCode: "00200573",
    preferredTableIds: ["0003427113"],
    tableTitleIncludes: ["消費者物価指数"],
    unit: "指数",
    calcMode: "yoy",
    changeType: "percent",
    selectors: { tab: "1", cat01: "0001", area: "00000" },
    periodStrategy: "timeCode",
    notes: "物価環境の把握に加え、実質購買力の背景理解にも役立ちます。",
    summary: true,
  },
  {
    id: "industrial-production",
    sourceType: "dashboard",
    category: "macro",
    title: "鉱工業生産指数",
    sourceName: "鉱工業(生産・出荷・在庫)指数の動向（確報）",
    preferredIndicatorCodes: ["0502070301000090010"],
    dashboard: { cycle: "1", regionalRank: "2", isSeasonalAdjustment: "2" },
    statSearchKeyword: "生産 季節調整済指数 2020年基準",
    statsCode: "00550300",
    preferredTableIds: ["0004015800"],
    tableTitleIncludes: ["付加価値額生産"],
    unit: "指数",
    calcMode: "mom",
    changeType: "percent",
    selectors: { cat01: "0001000" },
    periodStrategy: "timeCode",
    notes: "生産活動の強弱をみる景気指標で、製造業の温度感把握に向きます。",
    summary: true,
  },
  {
    id: "unemployment-rate",
    sourceType: "estat",
    category: "employment",
    title: "完全失業率",
    sourceName: "労働力調査 基本集計",
    statSearchKeyword: "完全失業率",
    statsCode: "00200531",
    preferredTableIds: ["0003005865"],
    tableTitleIncludes: ["完全失業率"],
    unit: "%",
    calcMode: "mom",
    changeType: "difference",
    selectors: {
      tab: "02",
      cat01: "000",
      cat02: "08",
      cat03: "0",
      area: "00000",
    },
    periodStrategy: "timeCode",
    notes: "雇用環境の変化を短時間で確認する基本指標です。",
    summary: true,
  },
  {
    id: "real-wage-index",
    sourceType: "dashboard",
    category: "employment",
    title: "実質賃金指数",
    sourceName: "毎月勤労統計調査 全国調査 長期時系列表",
    preferredIndicatorCodes: ["0302030201010090010"],
    dashboard: { cycle: "1", regionalRank: "2", isSeasonalAdjustment: "2" },
    statSearchKeyword: "季節調整済指数及び増減率 実質賃金",
    statsCode: "00450071",
    preferredTableIds: ["0003138106"],
    tableTitleIncludes: ["実質賃金", "季節調整済指数及び増減率"],
    unit: "指数",
    calcMode: "mom",
    changeType: "percent",
    selectors: {
      tab: "3003",
      cat02: "TL",
      cat03: "T",
      cat04: "00",
      area: "00000",
    },
    periodStrategy: "yearMonth",
    notes: "実質賃金は住宅設備やリフォームの消費環境を見る参考になります。",
    summary: true,
  },
  {
    id: "nominal-wage-index",
    sourceType: "dashboard",
    category: "employment",
    title: "名目賃金指数",
    sourceName: "毎月勤労統計調査 季節調整済指数",
    preferredIndicatorCodes: ["0302030202010090010"],
    dashboard: { cycle: "1", regionalRank: "2", isSeasonalAdjustment: "2" },
    statSearchKeyword: "季節調整済指数及び増減率 現金給与総額",
    statsCode: "00450071",
    preferredTableIds: ["0003138222"],
    tableTitleIncludes: ["現金給与総額", "季節調整済指数及び増減率"],
    unit: "指数",
    calcMode: "mom",
    changeType: "percent",
    selectors: {
      tab: "3003",
      cat02: "TL",
      cat03: "T",
      cat04: "00",
      area: "00000",
    },
    periodStrategy: "yearMonth",
    notes: "名目賃金の動きは企業と家計の感触を合わせて確認する際に便利です。",
    summary: true,
  },
  {
    id: "household-housing-spend",
    sourceType: "estat",
    category: "consumption",
    title: "家計調査 住居支出",
    sourceName: "家計調査 家計収支編 二人以上の世帯",
    statSearchKeyword: "住居",
    statsCode: "00200561",
    preferredTableIds: ["0002070001"],
    tableTitleIncludes: ["用途分類", "総数"],
    unit: "円",
    calcMode: "yoy",
    changeType: "percent",
    selectors: { tab: "01", cat01: "102", cat02: "03", area: "00000" },
    periodStrategy: "timeCode",
    notes: "住関連支出の変化をみる補助指標として活用できます。",
  },
  {
    id: "household-repair-maintenance",
    sourceType: "estat",
    category: "consumption",
    title: "家計調査 設備修繕・維持",
    sourceName: "家計調査 家計収支編 二人以上の世帯",
    statSearchKeyword: "設備修繕・維持",
    statsCode: "00200561",
    preferredTableIds: ["0002070001"],
    tableTitleIncludes: ["用途分類", "総数"],
    unit: "円",
    calcMode: "yoy",
    changeType: "percent",
    selectors: { tab: "01", cat01: "104", cat02: "03", area: "00000" },
    periodStrategy: "timeCode",
    notes: "修繕・維持支出は小規模改修や住設更新の気配をみる手掛かりです。",
  },
  {
    id: "household-furniture-housewares",
    sourceType: "estat",
    category: "consumption",
    title: "家計調査 家具・家事用品",
    sourceName: "家計調査 家計収支編 二人以上の世帯",
    statSearchKeyword: "家具・家事用品",
    statsCode: "00200561",
    preferredTableIds: ["0002070001"],
    tableTitleIncludes: ["用途分類", "総数"],
    unit: "円",
    calcMode: "yoy",
    changeType: "percent",
    selectors: { tab: "01", cat01: "112", cat02: "03", area: "00000" },
    periodStrategy: "timeCode",
    notes: "住設に近い耐久消費の空気感を補完的に確認できます。",
  },
];

export const REGIONAL_INDICATORS: IndicatorConfig[] = [
  {
    id: "pref-housing-starts-total",
    sourceType: "dashboard",
    category: "regional",
    title: "都道府県別 新設住宅着工戸数",
    sourceName: "住宅着工統計調査（建築着工統計調査）",
    searchKeyword: "新設住宅着工戸数",
    preferredIndicatorCodes: ["0802010103000010000"],
    regionSupport: "prefecture",
    unit: "戸",
    calcMode: "yoy",
    changeType: "percent",
    dashboard: { cycle: "1", isSeasonalAdjustment: "1", timeFromMonths: 84 },
    freshnessPolicy: { allowedCycles: ["month"], maxLagMonths: 4 },
    staleBehavior: "hide",
    notes: "統計ダッシュボード API から取得。地域別の住宅着工需要に使用します。",
  },
  {
    id: "pref-housing-starts-owner",
    sourceType: "dashboard",
    category: "regional",
    title: "都道府県別 持家着工戸数",
    sourceName: "住宅着工統計調査（建築着工統計調査）",
    searchKeyword: "持家 新設住宅着工戸数",
    preferredIndicatorCodes: ["0802010103010010010"],
    regionSupport: "prefecture",
    unit: "戸",
    calcMode: "yoy",
    changeType: "percent",
    dashboard: { cycle: "1", isSeasonalAdjustment: "1", timeFromMonths: 84 },
    freshnessPolicy: { allowedCycles: ["month"], maxLagMonths: 4 },
    staleBehavior: "hide",
  },
  {
    id: "pref-housing-starts-rental",
    sourceType: "dashboard",
    category: "regional",
    title: "都道府県別 貸家着工戸数",
    sourceName: "住宅着工統計調査（建築着工統計調査）",
    searchKeyword: "貸家 新設住宅着工戸数",
    preferredIndicatorCodes: ["0802010103010010020"],
    regionSupport: "prefecture",
    unit: "戸",
    calcMode: "yoy",
    changeType: "percent",
    dashboard: { cycle: "1", isSeasonalAdjustment: "1", timeFromMonths: 84 },
    freshnessPolicy: { allowedCycles: ["month"], maxLagMonths: 4 },
    staleBehavior: "hide",
  },
  {
    id: "pref-housing-starts-for-sale",
    sourceType: "dashboard",
    category: "regional",
    title: "都道府県別 分譲住宅着工戸数",
    sourceName: "住宅着工統計調査（建築着工統計調査）",
    searchKeyword: "分譲住宅 新設住宅着工戸数",
    preferredIndicatorCodes: ["0802010103010010030"],
    regionSupport: "prefecture",
    unit: "戸",
    calcMode: "yoy",
    changeType: "percent",
    dashboard: { cycle: "1", isSeasonalAdjustment: "1", timeFromMonths: 84 },
    freshnessPolicy: { allowedCycles: ["month"], maxLagMonths: 4 },
    staleBehavior: "hide",
  },
  {
    id: "pref-housing-floor-area",
    sourceType: "dashboard",
    category: "regional",
    title: "都道府県別 住宅着工床面積",
    sourceName: "住宅着工統計調査（建築着工統計調査）",
    searchKeyword: "着工新設住宅床面積",
    preferredIndicatorCodes: ["0802010203000010000"],
    regionSupport: "prefecture",
    unit: "㎡",
    calcMode: "yoy",
    changeType: "percent",
    dashboard: { cycle: "1", isSeasonalAdjustment: "1", timeFromMonths: 84 },
    freshnessPolicy: { allowedCycles: ["month"], maxLagMonths: 4 },
    staleBehavior: "hide",
    showIssueInSummary: false,
    notes: "API 上で月次の新しい系列が見つかる場合のみ表示します。",
  },
  {
    id: "pref-planned-construction-cost",
    sourceType: "dashboard",
    category: "regional",
    title: "都道府県別 工事費予定額",
    sourceName: "住宅着工統計調査（建築着工統計調査）",
    searchKeyword: "工事費予定額",
    preferredIndicatorCodes: ["0802010302000010010", "0802010301000010000"],
    regionSupport: "prefecture",
    unit: "万円",
    calcMode: "yoy",
    changeType: "percent",
    dashboard: { cycle: "1", isSeasonalAdjustment: "1", timeFromMonths: 84 },
    freshnessPolicy: { allowedCycles: ["month"], maxLagMonths: 4 },
    staleBehavior: "hide",
    showIssueInSummary: false,
    notes: "API 上で月次の新しい系列が見つかる場合のみ表示します。",
  },
  {
    id: "pref-public-construction-orders",
    sourceType: "dashboard",
    category: "regional",
    title: "都道府県別 公共工事受注額",
    sourceName: "建設工事受注動態統計調査（建設工事統計調査）",
    searchKeyword: "公共工事受注額",
    preferredIndicatorCodes: ["0802020202000010010"],
    regionSupport: "prefecture",
    unit: "百万円",
    calcMode: "yoy",
    changeType: "percent",
    dashboard: { cycle: "1", isSeasonalAdjustment: "1", timeFromMonths: 84 },
    freshnessPolicy: { allowedCycles: ["month"], maxLagMonths: 4 },
    staleBehavior: "hide",
    showIssueInSummary: false,
    notes: "都道府県別に取得できた場合のみ地域スコアへ使用します。",
  },
  {
    id: "pref-construction-orders-private-building",
    sourceType: "dashboard",
    category: "regional",
    title: "都道府県別 建設工事受注額（民間・建築）",
    sourceName: "建設工事受注動態統計調査（建設工事統計調査）",
    searchKeyword: "建設工事受注 民間 建築",
    regionSupport: "prefecture",
    unit: "百万円",
    calcMode: "yoy",
    changeType: "percent",
    dashboard: { cycle: "1", isSeasonalAdjustment: "1", timeFromMonths: 84 },
    freshnessPolicy: { allowedCycles: ["month"], maxLagMonths: 4 },
    staleBehavior: "hide",
    showIssueInSummary: false,
  },
  {
    id: "regional-housing-demand-score",
    sourceType: "computed",
    category: "regional",
    title: "地域住宅需要スコア",
    sourceName: "独自算出",
    derivedFrom: [
      "pref-housing-starts-total",
      "pref-housing-starts-owner",
      "pref-housing-starts-rental",
      "pref-housing-starts-for-sale",
      "pref-housing-floor-area",
      "pref-planned-construction-cost",
      "pref-public-construction-orders",
    ],
    unit: "score",
    calcMode: "computed",
    changeType: "score",
    regionSupport: "prefecture",
    freshnessPolicy: { allowedCycles: ["month"], maxLagMonths: 4 },
    staleBehavior: "hide",
    showIssueInSummary: false,
    notes: "住宅着工、床面積、工事費予定額、公共工事受注を標準化して合成した独自指標。",
  },
];
